### ISSUE TITLE
Work with 1.3

### ISSUE THREAD

**Issue by doodirock** [lithiumtech/angular-embedly#1]
Just checking to see if any testing has been done with 1.3 or if there are any pitfalls

**Comment by doodirock** [comment]
Seems to be working fine

**Comment by santthosh** [comment]
Thanks for testing this out @doodirock much appreciated

**Comment by doodirock** [comment]
No problem.  I am a bit confused as to how to properly use the module.  It seems like it comes with a built in directive which differs from the the custom directives you need to write.  

The service allows you to always pass the key to embedly by declaring it, however in the readme it says to add it to the directive itself.  I'm not really certain how to handle my use case from what I read.
